export type CapabilityFlag = {
  name: string;
  type: "string" | "boolean" | "number";
  required?: boolean;
  default?: string | number | boolean | null;
  description?: string;
};

export type CapabilityTarget = {
  required: boolean;
  write: boolean;
};

export type CapabilitySideEffects = {
  read: boolean;
  write: boolean;
  network: boolean;
};

export type CapabilityEntry = {
  id: string;
  command: string;
  subcommand?: string | null;
  summary: string;
  flags: CapabilityFlag[];
  target: CapabilityTarget;
  sideEffects: CapabilitySideEffects;
  preconditions: string[];
  output_schema?: string;
};

export const CAPABILITY_VERSION = 1;

export const CAPABILITIES: CapabilityEntry[] = [
  {
    id: "bb.show",
    command: "bb",
    subcommand: "show",
    summary: "Show a fresh blackboard view (read-only).",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "bb.post",
    command: "bb",
    subcommand: "post",
    summary: "Post an untrusted blackboard message.",
    flags: [
      {
        name: "--kind",
        type: "string",
        required: true,
        description: "Post kind (note|question|decision|warning).",
      },
      {
        name: "--text",
        type: "string",
        required: true,
        description: "Post text (untrusted).",
      },
      {
        name: "--block-id",
        type: "string",
        required: false,
        description: "Block id scope (block-####). Defaults to active block.",
      },
      {
        name: "--cycle-id",
        type: "string",
        required: false,
        description: "Cycle id scope (optional).",
      },
      {
        name: "--queue-id",
        type: "string",
        required: false,
        description: "Queue id scope (optional).",
      },
      {
        name: "--author",
        type: "string",
        required: false,
        description: "Author label (optional).",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "bb.export",
    command: "bb",
    subcommand: "export",
    summary: "Export blackboard posts to a deterministic JSON file.",
    flags: [
      {
        name: "--out",
        type: "string",
        required: true,
        description: "Repo-relative export path.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "bb.import",
    command: "bb",
    subcommand: "import",
    summary: "Import untrusted blackboard posts from a JSON export.",
    flags: [
      {
        name: "--from",
        type: "string",
        required: true,
        description: "Export file to import.",
      },
      {
        name: "--allow-external",
        type: "boolean",
        required: true,
        description: "Explicit opt-in to external posts.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "status",
    command: "status",
    summary: "Report cycle state and the next allowed action.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
    output_schema: "status.v2",
  },
  {
    id: "git.status",
    command: "git",
    subcommand: "status",
    summary: "Report deterministic git dirty-tree status (read-only).",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
    output_schema: "git-status.v2",
  },
  {
    id: "git.locks",
    command: "git",
    subcommand: "locks",
    summary: "Report .ato and .git lock state (read-only).",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
    output_schema: "git-locks.v1",
  },
  {
    id: "git.plan.clean",
    command: "git",
    subcommand: "plan clean",
    summary: "Produce a read-only deterministic clean-tree action plan.",
    flags: [
      {
        name: "--max-level",
        type: "string",
        required: false,
        description: "Maximum danger level to include (1|2|3, default 2).",
      },
      {
        name: "--include-level3",
        type: "boolean",
        required: false,
        description: "Include severe destructive proposals in plan output.",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
    output_schema: "git-plan-clean.v1",
  },
  {
    id: "git.plan.commit",
    command: "git",
    subcommand: "plan commit",
    summary: "Produce a read-only deterministic commit-workflow action plan.",
    flags: [
      {
        name: "--max-level",
        type: "string",
        required: false,
        description: "Maximum danger level to include (1|2|3, default 2).",
      },
      {
        name: "--include-level3",
        type: "boolean",
        required: false,
        description: "Include severe destructive proposals in plan output.",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
    output_schema: "git-plan-commit.v1",
  },
  {
    id: "git.plan.stash",
    command: "git",
    subcommand: "plan stash",
    summary: "Produce a read-only deterministic stash-workflow action plan.",
    flags: [
      {
        name: "--max-level",
        type: "string",
        required: false,
        description: "Maximum danger level to include (1|2|3, default 2).",
      },
      {
        name: "--include-level3",
        type: "boolean",
        required: false,
        description: "Include severe destructive proposals in plan output.",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
    output_schema: "git-plan-stash.v1",
  },
  {
    id: "git.plan.restore",
    command: "git",
    subcommand: "plan restore",
    summary: "Produce a read-only deterministic restore-workflow action plan.",
    flags: [
      {
        name: "--max-level",
        type: "string",
        required: false,
        description: "Maximum danger level to include (1|2|3, default 2).",
      },
      {
        name: "--include-level3",
        type: "boolean",
        required: false,
        description: "Include severe destructive proposals in plan output.",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
    output_schema: "git-plan-restore.v1",
  },
  {
    id: "baseline.verify",
    command: "baseline",
    subcommand: "verify",
    summary: "Verify baseline registry artifacts and tag integrity.",
    flags: [
      {
        name: "--tag",
        type: "string",
        required: true,
        description: "Baseline tag to verify.",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "block.seal.verify",
    command: "block",
    subcommand: "seal verify",
    summary: "Verify a block seal against current gate obligations.",
    flags: [
      {
        name: "--block-id",
        type: "string",
        required: true,
        description: "Block id to verify (e.g. block-0005).",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "block.report",
    command: "block",
    subcommand: "report",
    summary: "Generate a block report with ledger denominators and missing artifacts.",
    flags: [
      {
        name: "--block-id",
        type: "string",
        required: true,
        description: "Block id to report (e.g. block-0005).",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "block.close",
    command: "block",
    subcommand: "close",
    summary: "Close a block and write its closure report reference.",
    flags: [
      {
        name: "--block-id",
        type: "string",
        required: true,
        description: "Block id to close (e.g. block-0005).",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved.", "Protocol check must pass."],
  },
  {
    id: "block.open",
    command: "block",
    subcommand: "open",
    summary: "Open a new block and create a seal for current obligations.",
    flags: [
      {
        name: "--block-id",
        type: "string",
        required: true,
        description: "New block id to create (e.g. block-0006).",
      },
      {
        name: "--baseline",
        type: "string",
        required: true,
        description: "Baseline tag for the new block.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved.", "Protocol check must pass."],
  },
  {
    id: "capability.explain",
    command: "capability",
    subcommand: "explain",
    summary: "Explain a capability entry by id.",
    flags: [
      {
        name: "<id>",
        type: "string",
        required: true,
        description: "Capability id (e.g. q.add).",
      },
    ],
    target: { required: false, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: [],
  },
  {
    id: "capability.list",
    command: "capability",
    subcommand: "list",
    summary: "List available capability entries.",
    flags: [],
    target: { required: false, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: [],
  },
  {
    id: "contract.extract",
    command: "contract",
    subcommand: "extract",
    summary: "Extract contract sections.",
    flags: [
      {
        name: "--queue",
        type: "string",
        description: "Queue id to extract referenced sections.",
      },
      {
        name: "--doc",
        type: "string",
        description: "Contract document path.",
      },
      {
        name: "--section",
        type: "string",
        description: "Single section id or anchor.",
      },
      {
        name: "--sections",
        type: "string",
        description: "Comma-delimited section ids or anchors.",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Contract index must exist."],
  },
  {
    id: "contract.index",
    command: "contract",
    subcommand: "index",
    summary: "Index configured contract documents.",
    flags: [],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Contracts configured in .ato/config.json."],
  },
  {
    id: "fixture.generate",
    command: "fixture",
    subcommand: "generate",
    summary: "Generate type-based fixture data.",
    flags: [
      {
        name: "--file",
        type: "string",
        required: true,
        description: "TypeScript source file path.",
      },
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Type or interface name.",
      },
      {
        name: "--edge",
        type: "boolean",
        default: false,
        description: "Include edge-case variant.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "contract.compliance",
    command: "contract",
    subcommand: "compliance",
    summary: "Check contract compliance for documented commands.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "dashboard.build",
    command: "dashboard",
    subcommand: "build",
    summary: "Build dashboard assets into dist/dashboard.",
    flags: [],
    target: { required: false, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Node dependencies installed."],
  },
  {
    id: "dashboard.serve",
    command: "dashboard",
    subcommand: "serve",
    summary: "Serve dashboard over a local HTTP server.",
    flags: [
      { name: "--port", type: "number", default: 4173, description: "Port." },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: true },
    preconditions: ["Dashboard assets built or buildable."],
  },
  {
    id: "dev.run",
    command: "dev",
    subcommand: "run",
    summary: "Run a dev server and wait for readiness.",
    flags: [
      {
        name: "--command",
        type: "string",
        required: true,
        description: "Command to run.",
      },
      {
        name: "--url",
        type: "string",
        required: true,
        description: "Readiness URL to poll (expects HTTP 200).",
      },
      {
        name: "--timeout",
        type: "number",
        default: 60000,
        description: "Readiness timeout in milliseconds.",
      },
      {
        name: "--interval",
        type: "number",
        default: 500,
        description: "Readiness poll interval in milliseconds.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: true },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "trace.run",
    command: "trace",
    subcommand: "run",
    summary: "Run a command with runtime tracing.",
    flags: [
      {
        name: "--command",
        type: "string",
        required: true,
        description: "Command to run.",
      },
      {
        name: "--categories",
        type: "string",
        description: "Comma-delimited categories to record.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: true },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "diagnose",
    command: "diagnose",
    subcommand: null,
    summary: "Run diagnostics for node, target, protocol, lock, and gates.",
    flags: [],
    target: { required: false, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: [],
  },
  {
    id: "deps.build",
    command: "deps",
    subcommand: "build",
    summary: "Build and cache the dependency graph.",
    flags: [],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "deps.query",
    command: "deps",
    subcommand: "query",
    summary: "Query dependency impact for changed files.",
    flags: [
      {
        name: "--paths",
        type: "string",
        description: "Comma-delimited list of changed file paths.",
      },
      {
        name: "--refresh",
        type: "boolean",
        default: false,
        description: "Rebuild the dependency graph before query.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "deps.lint",
    command: "deps",
    subcommand: "lint",
    summary: "Detect dependency cycles and emit a report.",
    flags: [
      {
        name: "--refresh",
        type: "boolean",
        default: false,
        description: "Rebuild the dependency graph before lint.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "lock.status",
    command: "lock",
    subcommand: "status",
    summary: "Report lock status and staleness.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "lock.clear",
    command: "lock",
    subcommand: "clear",
    summary: "Clear a stale lock when --force is provided.",
    flags: [
      {
        name: "--force",
        type: "boolean",
        default: false,
        description: "Allow clearing stale locks.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved.", "Protocol compatibility required."],
  },
  {
    id: "docs.delta",
    command: "docs",
    subcommand: "delta",
    summary: "Generate documentation delta report.",
    flags: [
      {
        name: "--patch",
        type: "boolean",
        default: false,
        description: "Emit patch suggestions for docs.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "docs.truth",
    command: "docs",
    subcommand: "truth",
    summary: "Validate truth labels and evidence pointers in major docs.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "memory.snapshot",
    command: "memory",
    subcommand: "snapshot",
    summary: "Write a working-memory snapshot.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Snapshot type (working|state).",
      },
      {
        name: "--summary",
        type: "string",
        required: true,
        description: "Snapshot summary.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "memory.show",
    command: "memory",
    subcommand: "show",
    summary: "Show the latest working-memory snapshot.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Snapshot type (working|state).",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "memory.query",
    command: "memory",
    subcommand: "query",
    summary: "Query episodic memory entries.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Memory type (episodic).",
      },
      {
        name: "--after",
        type: "string",
        description: "Filter by start timestamp (inclusive).",
      },
      {
        name: "--before",
        type: "string",
        description: "Filter by end timestamp (inclusive).",
      },
      {
        name: "--kind",
        type: "string",
        description: "Filter by run log kind.",
      },
      {
        name: "--command",
        type: "string",
        description: "Filter by command substring.",
      },
      {
        name: "--outcome",
        type: "string",
        description: "Filter by outcome (ok|fail|unknown).",
      },
      {
        name: "--limit",
        type: "number",
        description: "Limit results.",
      },
      {
        name: "--refresh",
        type: "boolean",
        default: false,
        description: "Rebuild episodic index before query.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "memory.commit",
    command: "memory",
    subcommand: "commit",
    summary: "Add a commitment entry.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Memory type (commitment).",
      },
      {
        name: "--scope",
        type: "string",
        required: true,
        description: "Commitment scope.",
      },
      {
        name: "--owner",
        type: "string",
        required: true,
        description: "Commitment owner.",
      },
      {
        name: "--summary",
        type: "string",
        required: true,
        description: "Commitment summary.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "memory.list",
    command: "memory",
    subcommand: "list",
    summary: "List commitment entries.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Memory type (commitment).",
      },
      {
        name: "--scope",
        type: "string",
        description: "Filter by scope.",
      },
      {
        name: "--status",
        type: "string",
        description: "Filter by status (open|resolved).",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "memory.resolve",
    command: "memory",
    subcommand: "resolve",
    summary: "Resolve a commitment entry.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Memory type (commitment).",
      },
      {
        name: "--id",
        type: "string",
        required: true,
        description: "Commitment id.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "memory.build",
    command: "memory",
    subcommand: "build",
    summary: "Build the entity memory graph.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Memory type (entity).",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "memory.record",
    command: "memory",
    subcommand: "record",
    summary: "Record a procedural memory entry.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Memory type (procedural).",
      },
      {
        name: "--input",
        type: "string",
        required: true,
        description: "Procedural entry payload (JSON or path).",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "memory.run",
    command: "memory",
    subcommand: "run",
    summary: "Run a procedural memory entry.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Memory type (procedural).",
      },
      {
        name: "--id",
        type: "string",
        required: true,
        description: "Procedural entry id.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "session.closeout",
    command: "session",
    subcommand: "closeout",
    summary: "Generate or apply a session closeout plan (plan|apply).",
    flags: [
      { name: "--gate-run", type: "string" },
      { name: "--apply", type: "boolean", default: false },
      { name: "--dest", type: "string" },
      { name: "--allow-cross-store-write", type: "boolean", default: false },
      { name: "--telemetry-ref", type: "string" },
      { name: "--force", type: "boolean", default: false },
    ],
    target: { required: false, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved when applying."],
  },
  {
    id: "memory.link",
    command: "memory",
    subcommand: "link",
    summary: "Record a causal link.",
    flags: [
      {
        name: "--type",
        type: "string",
        required: true,
        description: "Memory type (causal).",
      },
      {
        name: "--command",
        type: "string",
        description: "Command to link.",
      },
      {
        name: "--file",
        type: "string",
        description: "File to link.",
      },
      {
        name: "--outcome",
        type: "string",
        required: true,
        description: "Outcome description.",
      },
      {
        name: "--confidence",
        type: "number",
        required: true,
        description: "Confidence score (0-1).",
      },
      {
        name: "--queue",
        type: "string",
        description: "Optional queue id provenance.",
      },
      {
        name: "--run",
        type: "string",
        description: "Optional run id provenance.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "gate.explain",
    command: "gate",
    subcommand: "explain",
    summary: "Explain configured gates.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: [],
  },
  {
    id: "gate.run",
    command: "gate",
    subcommand: "run",
    summary: "Run configured gates.",
    flags: [
      {
        name: "--mode",
        type: "string",
        default: "recommended",
        description: "Gate mode (fast|full). Defaults to recommendation.",
      },
      {
        name: "--explain",
        type: "boolean",
        default: false,
        description: "Explain risk triggers and touched surfaces.",
      },
      {
        name: "--report-touched",
        type: "boolean",
        default: false,
        description: "Print touched files per gate step.",
      },
      {
        name: "--heartbeat",
        type: "string",
        description: "Emit heartbeat lines every N seconds during steps.",
      },
      {
        name: "--no-browser",
        type: "boolean",
        default: false,
        description: "Skip browser/listen-requiring gate steps.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Gates configured in .ato/config.json."],
  },
  {
    id: "init",
    command: "init",
    subcommand: null,
    summary: "Initialize a repo-local .ato store.",
    flags: [
      { name: "--id", type: "string", description: "Target id." },
    ],
    target: { required: false, write: true },
    sideEffects: { read: false, write: true, network: false },
    preconditions: [],
  },
  {
    id: "impact.build",
    command: "impact",
    subcommand: "build",
    summary: "Build and cache the impact graph.",
    flags: [],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "impact.query",
    command: "impact",
    subcommand: "query",
    summary: "Query impacted packages/tests for changed files.",
    flags: [
      {
        name: "--paths",
        type: "string",
        description: "Comma-delimited list of changed file paths.",
      },
      {
        name: "--refresh",
        type: "boolean",
        default: false,
        description: "Rebuild the graph before querying.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "lesson.add",
    command: "lesson",
    subcommand: "add",
    summary: "Add a lesson entry to the store.",
    flags: [
      {
        name: "--input",
        type: "string",
        required: true,
        description: "JSON payload or path to JSON file.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: [],
  },
  {
    id: "lint.protocol",
    command: "lint",
    subcommand: "protocol",
    summary: "Lint protocol metadata in AGENTS.md.",
    flags: [],
    target: { required: false, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: [],
  },
  {
    id: "lint.terms",
    command: "lint",
    subcommand: "terms",
    summary: "Lint terminology requirements against the repo.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "cycle.start",
    command: "cycle",
    subcommand: "start",
    summary: "Run eval preflight, selection, and queue start as one step.",
    flags: [],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved.", "Protocol check must pass."],
  },
  {
    id: "cycle.finish",
    command: "cycle",
    subcommand: "finish",
    summary: "Run acceptance checks, full gate, queue done, and eval record.",
    flags: [],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Active cycle state must exist."],
  },
  {
    id: "cycle.abort",
    command: "cycle",
    subcommand: "abort",
    summary: "Abort the active cycle and revert the queue item to queued.",
    flags: [
      {
        name: "--reason",
        type: "string",
        required: true,
        description: "Reason for aborting the cycle.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Active cycle state must exist."],
  },
  {
    id: "pack",
    command: "pack",
    subcommand: null,
    summary: "Generate a context pack.",
    flags: [
      { name: "--task", type: "string", required: true, description: "Task." },
      {
        name: "--budget",
        type: "number",
        default: 2400,
        description: "Token budget.",
      },
      { name: "--queue", type: "string", description: "Queue id." },
      { name: "--focus", type: "string", description: "Focus tag." },
      { name: "--format", type: "string", default: "md", description: "md|json." },
      {
        name: "--with-citations",
        type: "boolean",
        description: "Include citation metadata in pack output.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "pack.verify",
    command: "pack",
    subcommand: "verify",
    summary: "Verify a cycle evidence pack.",
    flags: [
      {
        name: "--path",
        type: "string",
        required: true,
        description: "Path to the pack tarball.",
      },
      {
        name: "--manifest",
        type: "string",
        description: "Optional manifest path override.",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "plugin.add",
    command: "plugin",
    subcommand: "add",
    summary: "Register a local plugin manifest.",
    flags: [
      {
        name: "--input",
        type: "string",
        required: true,
        description: "Plugin manifest JSON or path to JSON file.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Plugin entry path must exist within target root."],
  },
  {
    id: "pattern.add",
    command: "pattern",
    subcommand: "add",
    summary: "Add a pattern entry to the store.",
    flags: [
      {
        name: "--input",
        type: "string",
        required: true,
        description: "JSON payload or path to JSON file.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: [],
  },
  {
    id: "pattern.apply",
    command: "pattern",
    subcommand: "apply",
    summary: "Apply a pattern entry.",
    flags: [
      {
        name: "--id",
        type: "string",
        required: true,
        description: "Pattern id.",
      },
      {
        name: "--queue",
        type: "string",
        description: "Queue id provenance.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Pattern must exist."],
  },
  {
    id: "protocol.check",
    command: "protocol",
    subcommand: "check",
    summary: "Check protocol compatibility.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "q.add",
    command: "q",
    subcommand: "add",
    summary: "Add a queue item.",
    flags: [
      { name: "--type", type: "string", default: "feature" },
      {
        name: "--queue-target",
        type: "string",
        required: true,
        description: "Queue target selector.",
      },
      { name: "--priority", type: "string", default: "P2" },
      { name: "--problem", type: "string", required: true },
      { name: "--outcome", type: "string", required: true },
      { name: "--plan-steps", type: "string", required: true },
      { name: "--plan-rationale", type: "string", required: false },
      { name: "--acceptance", type: "string", required: true },
      { name: "--inputs", type: "string", required: true },
      { name: "--deliverables", type: "string", required: true },
      { name: "--contract-refs", type: "string", required: false },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "q.intake",
    command: "q",
    subcommand: "intake",
    summary: "Ingest a queue item from a candidate JSON file.",
    flags: [
      { name: "--file", type: "string", required: true },
      { name: "--dest", type: "string", description: "Destination store for cross-store intake." },
      { name: "--allow-cross-store-write", type: "boolean", default: false },
      { name: "--dry-run", type: "boolean", default: false },
      { name: "--telemetry-ref", type: "string" },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "q.transfer",
    command: "q",
    subcommand: "transfer",
    summary: "Transfer a queue item from a source repo into the target.",
    flags: [
      {
        name: "--dest",
        type: "string",
        description: "Destination target id or path.",
      },
      { name: "--allow-cross-store-write", type: "boolean", default: false },
      {
        name: "--source",
        type: "string",
        description: "Source repo id or path.",
      },
      { name: "--all", type: "boolean", default: false },
      { name: "--status", type: "string" },
      { name: "--dry-run", type: "boolean", default: false },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "q.contract_refs.fix",
    command: "q",
    subcommand: "contract-refs",
    summary: "Fix contract refs for cross-repo closeout using a destination contract index.",
    flags: [
      { name: "--ids", type: "string", required: true },
      { name: "--dest", type: "string", description: "Destination repo id or path." },
      { name: "--apply", type: "boolean", default: false },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Destination contract index must exist."],
  },
  {
    id: "q.list",
    command: "q",
    subcommand: "list",
    summary: "List queue items.",
    flags: [
      {
        name: "--status",
        type: "string",
        description: "Filter by queue status.",
      },
      {
        name: "--tag",
        type: "string",
        description: "Filter by tag.",
      },
      {
        name: "--queue-target",
        type: "string",
        description: "Filter by queue target selector.",
      },
      {
        name: "--owner",
        type: "string",
        description: "Filter by owner.",
      },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
    output_schema: "queue-list.v1",
  },
  {
    id: "q.trace",
    command: "q",
    subcommand: "trace",
    summary: "Show origin-aware investigation hints for a queue item.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Queue item must exist."],
  },
  {
    id: "q.update",
    command: "q",
    subcommand: "update",
    summary: "Update a queue item via JSON patch or deterministic flags.",
    flags: [
      {
        name: "--input",
        type: "string",
        required: false,
        description: "JSON patch object or file path (mutually exclusive with flags).",
      },
      {
        name: "--priority",
        type: "string",
        required: false,
        description: "Set priority (P0..P4 or 0..4).",
      },
      {
        name: "--status",
        type: "string",
        required: false,
        description: "Set status (queued|blocked|dropped).",
      },
      {
        name: "--queue-target",
        type: "string",
        required: false,
        description: "Set queue target (exact|range|milestone).",
      },
      {
        name: "--add-tag",
        type: "string",
        required: false,
        description: "Add tag (repeatable).",
      },
      {
        name: "--remove-tag",
        type: "string",
        required: false,
        description: "Remove tag (repeatable).",
      },
      {
        name: "--note",
        type: "string",
        required: false,
        description: "Append note (repeatable).",
      },
      {
        name: "--outcome",
        type: "string",
        required: false,
        description: "Set spec.outcome.",
      },
      {
        name: "--plan-steps",
        type: "string",
        required: false,
        description: "Replace spec.plan.steps (pipe-delimited).",
      },
      {
        name: "--plan-rationale",
        type: "string",
        required: false,
        description: "Set spec.plan.rationale.",
      },
      {
        name: "--acceptance-add",
        type: "string",
        required: false,
        description: "Append acceptance check (repeatable).",
      },
      {
        name: "--acceptance-set",
        type: "string",
        required: false,
        description: "Replace acceptance criteria from @file.json.",
      },
      {
        name: "--evidence-add",
        type: "string",
        required: false,
        description: "Append evidence entry (repeatable).",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Queue item must exist."],
  },
  {
    id: "q.validate",
    command: "q",
    subcommand: "validate",
    summary: "Validate queue items.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Contract index must exist if contract refs used."],
    output_schema: "queue-validate.v1",
  },
  {
    id: "q.view",
    command: "q",
    subcommand: "view",
    summary: "Regenerate queue views.",
    flags: [],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: [],
  },
  {
    id: "reflect.record",
    command: "reflect",
    subcommand: "record",
    summary: "Record a reflection entry.",
    flags: [
      { name: "--id", type: "string", required: true },
      { name: "--input", type: "string", required: true },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Queue item must exist."],
  },
  {
    id: "reflect.run",
    command: "reflect",
    subcommand: "run",
    summary: "Generate a reflection report.",
    flags: [
      { name: "--queue", type: "string", required: true },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Queue item must exist."],
  },
  {
    id: "refactor.rename",
    command: "refactor",
    subcommand: "rename",
    summary: "Rename a symbol across JS/TS files.",
    flags: [
      {
        name: "--from",
        type: "string",
        required: true,
        description: "Symbol to rename.",
      },
      {
        name: "--to",
        type: "string",
        required: true,
        description: "New symbol name.",
      },
      {
        name: "--paths",
        type: "string",
        description: "Comma-delimited roots/files to scan.",
      },
      {
        name: "--apply",
        type: "boolean",
        default: false,
        description: "Apply changes (default: preview).",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "refactor.rollback",
    command: "refactor",
    subcommand: "rollback",
    summary: "Rollback a refactor bundle.",
    flags: [
      {
        name: "--id",
        type: "string",
        required: true,
        description: "Rollback bundle id.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Rollback bundle must exist."],
  },
  {
    id: "scaffold",
    command: "scaffold",
    subcommand: null,
    summary: "Generate code scaffolding from a spec.",
    flags: [
      {
        name: "--input",
        type: "string",
        required: true,
        description: "Scaffold spec JSON or path to JSON file.",
      },
      {
        name: "--dry-run",
        type: "boolean",
        default: false,
        description: "Preview planned outputs without writing files.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "route.index",
    command: "route",
    subcommand: "index",
    summary: "Index routers for scoped packs.",
    flags: [],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: [],
  },
  {
    id: "route.pack",
    command: "route",
    subcommand: "pack",
    summary: "Print the best router pack for a path.",
    flags: [
      { name: "--path", type: "string", required: true },
    ],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Router index should be available."],
  },
  {
    id: "self.rollback",
    command: "self",
    subcommand: "rollback",
    summary: "Rollback to a previous CLI build.",
    flags: [],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: true },
    preconditions: ["Previous self-update provenance exists."],
  },
  {
    id: "self.update",
    command: "self",
    subcommand: "update",
    summary: "Build, test, and install a new CLI build.",
    flags: [
      { name: "--dry-run", type: "boolean", default: false },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: true },
    preconditions: ["Node dependencies installed."],
  },
  {
    id: "repo.init-seed",
    command: "repo",
    subcommand: "init-seed",
    summary: "Regenerate repo fingerprint seed.",
    flags: [],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: [],
  },
  {
    id: "repo.list",
    command: "repo",
    subcommand: "list",
    summary: "List registered repos.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: [],
  },
  {
    id: "repo.resolve",
    command: "repo",
    subcommand: "resolve",
    summary: "Resolve repo selection.",
    flags: [],
    target: { required: false, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: [],
  },
  {
    id: "test.select",
    command: "test",
    subcommand: "select",
    summary: "Select tests based on impacted files.",
    flags: [
      {
        name: "--paths",
        type: "string",
        description: "Comma-delimited list of changed files.",
      },
      {
        name: "--full",
        type: "boolean",
        default: false,
        description: "Select full test suite.",
      },
      {
        name: "--explain",
        type: "boolean",
        default: false,
        description: "Include edges that led to each test.",
      },
      {
        name: "--refresh",
        type: "boolean",
        default: false,
        description: "Rebuild impact graph before selection.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "eval.scorecard",
    command: "eval",
    subcommand: "scorecard",
    summary: "Show the current eval scorecard.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "signal.definition.list",
    command: "signal",
    subcommand: "definition list",
    summary: "List signal definitions from the catalog.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "signal.definition.validate",
    command: "signal",
    subcommand: "definition validate",
    summary: "Validate the signal definition catalog against schema.",
    flags: [],
    target: { required: true, write: false },
    sideEffects: { read: true, write: false, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "telemetry.codex.ingest",
    command: "telemetry",
    subcommand: "codex ingest",
    summary: "Ingest Codex sessions into normalized telemetry summaries.",
    flags: [
      {
        name: "--path",
        type: "string",
        required: false,
        description: "Codex sessions JSONL file or directory.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
  {
    id: "telemetry.codex.report",
    command: "telemetry",
    subcommand: "codex report",
    summary: "Aggregate Codex telemetry into signal reports.",
    flags: [
      {
        name: "--since",
        type: "string",
        required: false,
        description: "Filter sessions started on/after timestamp.",
      },
      {
        name: "--git-commit",
        type: "string",
        required: false,
        description: "Filter sessions by git commit hash.",
      },
      {
        name: "--cycle-id",
        type: "string",
        required: false,
        description: "Optional cycle id for report artifact naming.",
      },
    ],
    target: { required: true, write: true },
    sideEffects: { read: true, write: true, network: false },
    preconditions: ["Target must be resolved."],
  },
];
